swagger: "2.0"
info:
  title: API de Usuários e Indivíduos
  description: API para gerenciamento de usuários e indivíduos com autenticação JWT.
  version: "1.0"

paths:
  /auth/login:
    post:
      summary: Autentica um usuário e retorna um token JWT
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
                example: "usuario@email.com"
              password:
                type: string
                example: "senha123"
      responses:
        200:
          description: Token JWT gerado com sucesso
          schema:
            type: object
            properties:
              token:
                type: string
        400:
          description: Email e senha são obrigatórios
        401:
          description: Credenciais inválidas

  /users:
    get:
      summary: Retorna a lista de usuários
      responses:
        200:
          description: Lista de usuários retornada com sucesso
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                email:
                  type: string
    post:
      summary: Cria um novo usuário
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        201:
          description: Usuário criado com sucesso
        400:
          description: Nome, email e senha são obrigatórios ou email já existe

  /users/{user_id}:
    get:
      summary: Retorna um usuário específico
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
      responses:
        200:
          description: Usuário encontrado
        404:
          description: Usuário não encontrado
    put:
      summary: Atualiza um usuário
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
              email:
                type: string
              password:
                type: string
      responses:
        200:
          description: Usuário atualizado com sucesso
        404:
          description: Usuário não encontrado
    delete:
      summary: Exclui um usuário
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
      responses:
        200:
          description: Usuário excluído com sucesso
        404:
          description: Usuário não encontrado

  /individuals:
    get:
      summary: Retorna todos os indivíduos do usuário autenticado
      security:
        - Bearer: []
      responses:
        200:
          description: Lista de indivíduos retornada com sucesso
    post:
      summary: Cria um novo indivíduo
      security:
        - Bearer: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              identificator:
                type: string
              descricao:
                type: string
              f_sa:
                type: number
              f_lr:
                type: number
              md_si:
                type: number
              f_sr:
                type: number
              f_si:
                type: number
              f_sl:
                type: number
              e_ap:
                type: number
              img:
                type: string
      responses:
        201:
          description: Indivíduo criado com sucesso
        400:
          description: Parâmetros obrigatórios ausentes

  /individuals/{individual_id}:
    get:
      summary: Retorna um indivíduo específico
      security:
        - Bearer: []
      parameters:
        - in: path
          name: individual_id
          required: true
          type: integer
      responses:
        200:
          description: Indivíduo encontrado
        404:
          description: Indivíduo não encontrado
    put:
      summary: Atualiza um indivíduo
      security:
        - Bearer: []
      parameters:
        - in: path
          name: individual_id
          required: true
          type: integer
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              identificator:
                type: string
              sexo:
                type: string
              descricao:
                type: string
              f_sa:
                type: number
              f_lr:
                type: number
              md_si:
                type: number
              f_sr:
                type: number
              f_si:
                type: number
              f_sl:
                type: number
              e_ap:
                type: number
              img:
                type: string
      responses:
        200:
          description: Indivíduo atualizado com sucesso
        404:
          description: Indivíduo não encontrado
    delete:
      summary: Exclui um indivíduo
      security:
        - Bearer: []
      parameters:
        - in: path
          name: individual_id
          required: true
          type: integer
      responses:
        200:
          description: Indivíduo excluído com sucesso
        404:
          description: Indivíduo não encontrado

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
